FROM node

WORKDIR /app

COPY package.json ./

RUN npm install --legacy-peer-deps

COPY . .

ENV REACT_APP_BASE_URL=http://localhost:5000/api/v1

EXPOSE 3000

CMD [ "npm", "start" ]






# FROM node:14-slim

# WORKDIR /usr/src/app

# COPY ./package.json ./
# COPY ./yarn.lock ./

# RUN yarn install

# COPY . .

# ENV REACT_APP_BASE_URL=http://localhost:5000/api

# EXPOSE 3000

# CMD [ "yarn", "start" ]